WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 22, in login
    userId=request.POST['userId'], userPw=request.POST['userPw'])
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view onePage.login.login didn't return an HttpResponse object. It returned None instead.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 27, in login
    return HttpResponse("<script>alert('아이디 혹은 비밀번호를 잘못 입력하셨습니다.')</script>")
NameError: name 'html' is not defined
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 23, in login
    userId=request.POST['userId'], userPw=request.POST['userPw'])
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 22, in login
    userId=request.POST('userId', False), userPw=request.POST.get('userPw', False))
TypeError: 'QueryDict' object is not callable
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 22, in login
    userId=request.POST('userId', False), userPw=request.POST.get('userPw', False))
TypeError: 'QueryDict' object is not callable
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.POST.get('Content-Encoding', '')
AttributeError: 'HttpResponse' object has no attribute 'POST'
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.POST.get('Content-Encoding', '')
AttributeError: 'HttpResponseNotFound' object has no attribute 'POST'
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view onePage.login.login didn't return an HttpResponse object. It returned None instead.
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 29, in login
    return get_response(request)
NameError: name 'get_response' is not defined
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 21, in login
    print(request.POSt)
AttributeError: 'WSGIRequest' object has no attribute 'POSt'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 21, in login
    print(request.POSt.get["userId"])
AttributeError: 'WSGIRequest' object has no attribute 'POSt'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 21, in login
    print(request.POST.get["userId"])
TypeError: 'method' object is not subscriptable
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 20, in login
    print(request.POST.get["userId"])
TypeError: 'method' object is not subscriptable
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 20, in login
    print(request.POST.get["userId"])
TypeError: 'method' object is not subscriptable
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 20, in login
    print(request.POST.get["userId"])
TypeError: 'method' object is not subscriptable
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 20, in login
    print(request.POST["userId"])
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 20, in login
    print(request.POST["userId"])
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 20, in login
    print(request.POST["userId"])
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 25, in login
    print(content)
UnboundLocalError: local variable 'content' referenced before assignment
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 28, in login
    userId=request.POST['userId'],
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 28, in login
    userId=request.POST['userId'],
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 28, in login
    userId=request.POST['userId'],
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 22, in login
    request_data = json.loads(request_data)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 23, in login
    request_data = json.loads(request_data)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 23, in login
    request_data = json.loads(request_data)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 27, in login
    if userModel.exists():
UnboundLocalError: local variable 'userModel' referenced before assignment
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 28, in login
    if userModel.exists():
AttributeError: 'list' object has no attribute 'exists'
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 28, in login
    if userModel.exists():
AttributeError: module 'onePage.models' has no attribute 'exists'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'userId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 22, in login
    userId = request.POST['userId']
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'userId'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 31, in login
    if userModel.exists():
UnboundLocalError: local variable 'userModel' referenced before assignment
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Playdata\Desktop\port\SA\portfolio\onePage\login.py", line 33, in login
    if userModel.exists():
AttributeError: module 'onePage.models' has no attribute 'exists'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /onePage/login/
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\http\response.py", line 156, in get
    return self._headers.get(header.lower(), (None, alternate))[1]
AttributeError: 'str' object has no attribute '_headers'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\http\response.py", line 156, in get
    return self._headers.get(header.lower(), (None, alternate))[1]
AttributeError: 'str' object has no attribute '_headers'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\http\response.py", line 156, in get
    return self._headers.get(header.lower(), (None, alternate))[1]
AttributeError: 'str' object has no attribute '_headers'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /img/portfolio/folio02.jpg
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
WARNING:django.request:Not Found: /img/portfolio/folio04.jpg
WARNING:django.request:Not Found: /img/portfolio/folio05.jpg
WARNING:django.request:Not Found: /img/portfolio/folio06.jpg
WARNING:django.request:Not Found: /img/portfolio/folio03.jpg
WARNING:django.request:Not Found: /lib/php-mail-form/loading.gif
WARNING:django.request:Not Found: /img/portfolio/folio01.jpg
ERROR:django.request:Internal Server Error: /onePage/login/
Traceback (most recent call last):
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\deprecation.py", line 93, in __call__
    response = self.process_response(request, response)
  File "C:\Users\Playdata\AppData\Local\Programs\Python\Python36\lib\site-packages\debug_toolbar\middleware.py", line 107, in process_response
    content_encoding = response.get('Content-Encoding', '')
AttributeError: 'WSGIRequest' object has no attribute 'get'
WARNING:django.request:Not Found: /favicon.ico
